### ISSUE TITLE
Feature: validate MP count instead of individual dimensions

### ISSUE THREAD

**Issue by SanderVanLeeuwen** [pqina/filepond-plugin-image-validate-size#1]
Would it be possible to support validating the total pixel count instead of the individual dimensions? For example, I would like to set a minimum amount of 16MP image uploads. This is met by both an image of 4000x4000px and one of 2000x8000px. I don't want to set the minimum width & height parameters to 2000px though, as this would also allow uploads of only 4MP.

I quickly tried abusing the custom `imageValidateSizeMeasure` method, but that doesn't seem to be possible in this case. Is there any other way I could accomplish this?

**Comment by rikschennink** [comment]
Sounds like a nice addition! Will add this in the near future.

**Comment by SanderVanLeeuwen** [comment]
Cool!

Come to think of it, maybe implementing a callback method for this too (like the `imageValidateSizeMeasure`) would be the most flexible? I can imagine there are a lot of possible configuration requirements which slightly differ from case to case. For example my case above would require 16MP images, but would then allow images of 1 x 16.000 or 2 x 8000 which is also undesirable.

So, in our case we would need to limit the image size to 16MP with a minimum width _or_ height of ~2000px. But that is probably something I should implement myself in a callback instead of you taking all these edge cases into account ;)

**Comment by rikschennink** [comment]
Just published version `1.2.0`. Added the `imageValidateSizeMinResolution` and `imageValidateSizeMaxResolution` properties.

You can set the minimum width and minimum height plus a required minimum resolution, I think this covers your use case, let me know if it doesn't.

**Comment by SanderVanLeeuwen** [comment]
Works like a charm! 🤩

One very minor detail; the error message is not too user friendly because it shows the actual pixel amount. "Minimum resolution is 16000000 pixels" is quite hard to read. An extra variable `{minResolutionMp}` with the resolution divided by 1M would solve that. But if that's too much, I'm happy as it is now ;)

**Comment by rikschennink** [comment]
Fantastic! I agree the label is not fantastic, I decided to leave it for now but might improve on that in the future.

**Comment by davoodmood** [comment]
Is it possible to validate the image based on a set of height and weight relative sizes? This would be useful for multiple image file upload to have an array of dimensions for validation:
``` JSON
[
{ width: 720, height: 90 },
{ width: 460, height: 60 },
{ width: 600, height: 600}
]
```
Please tell me if there is already a solution for this.

**Comment by rikschennink** [comment]
@davoodmood there is no solution for this. I'd advise to fork the plugin or submit a PR.
