### ISSUE TITLE
imageValidateSizeMeasure is only called when browser can't determine the size

### ISSUE THREAD

**Issue by alexandernst** [pqina/filepond-plugin-image-validate-size#2]
I'm trying to use `imageValidateSizeMeasure`, but the function just doesn't seem to be called in any way.

I checked the source code and indeed the `imageValidateSizeMeasure` reference shows up only once, which makes me believe that the function isn't called from anywhere.

**Comment by rikschennink** [comment]
[It's run on line 81](https://github.com/pqina/filepond-plugin-image-validate-size/blob/master/src/js/index.js#L81)

**Comment by rikschennink** [comment]
Accidentally pressed Close. : )

**Comment by alexandernst** [comment]
🤔 Maybe then I'm doing something wrong, but I don't see what. Can you spot what's wrong with it?

```
FilePond.create(
	input,
	{
		allowMultiple: true,
		allowRevert: false,
		imagePreviewMaxHeight: 512,

		// https://github.com/pqina/filepond-plugin-image-validate-size/issues/2
		imageValidateSizeMeasure: function(file) {
			debugger;
			return new Promise(function(resolve, reject) {
				debugger;
			});
		}
	}
);
```

**Comment by rikschennink** [comment]
It's only called when the image dropped is not supported by the browser/ the browser cannot determine the width and height.

**Comment by alexandernst** [comment]
Oh, bummer. Isn't there a callback that is called whenever any image is added? My use case is that, aside from the image size, I must validate the name (my users are allowed to upload images only following certain name patterns).

**Comment by rikschennink** [comment]
I think you can use `beforeAddFile`, if not, you can fork one of the plugins and modify it accordingly. I guess [File Validate Size](https://github.com/pqina/filepond-plugin-file-validate-size) is the easiest one to fork if needed.

**Comment by ilchin** [comment]
不知道这个有没有解决呢？我也是同样的问题，imageValidateSizeMeasure 没有起作用。

**Comment by rikschennink** [comment]
@ilchin see last comment by @rikschennink
