### ISSUE TITLE
Contribute - Typescript Type

### ISSUE THREAD

**Issue by engdlee** [pqina/filepond-plugin-image-validate-size#3]
Hello,

I needed this plugin but with his type, since it doesnt have one i created one, how can i contribute, should i create a fork and PR to it?

**Comment by rikschennink** [comment]
If it follows the same pattern as the other plugin TypeScript files (see here: https://github.com/pqina/filepond-plugin-file-rename/pull/8/files) then I'm happy to accept a PR

**Comment by engdlee** [comment]
yeah, same pattern,
![image](https://user-images.githubusercontent.com/25491657/87881433-37333880-c9c7-11ea-94e5-4f2dfdf7a2bb.png)

**Comment by joelbourbon** [comment]
This was merged I feel like. This could be closed.
